const RSVP_SESSION_KEY="weddingRsvpSession";
const loginForm=document.querySelector("#loginForm"),loginStatus=document.querySelector("#loginStatus"),loginButton=document.querySelector("#loginSubmit");
loginForm.onsubmit=login;
restoreSession();

async function login(event){event.preventDefault();loginButton.disabled=true;loginStatus.textContent="Logging in…";try{const config=await getConfig();const response=await fetch(`${config.supabaseUrl}/auth/v1/token?grant_type=password`,{method:"POST",headers:{apikey:config.anonKey,"Content-Type":"application/json"},body:JSON.stringify({email:document.querySelector("#email").value.trim(),password:document.querySelector("#password").value})});const result=await response.json();if(!response.ok)throw new Error(result.error_description||result.msg||result.message||"Invalid login credentials.");localStorage.setItem(RSVP_SESSION_KEY,JSON.stringify(result));window.location.replace("rsvp.html")}catch(error){loginStatus.textContent=error.message}finally{loginButton.disabled=false}}

async function restoreSession(){const params=new URLSearchParams(location.search),stored=localStorage.getItem(RSVP_SESSION_KEY);if(!stored){if(params.has("expired"))loginStatus.textContent="Your session expired. Please log in again.";else if(params.has("rsvp"))loginStatus.textContent="Log in to view or update your RSVP.";return}try{const config=await getConfig();let session=JSON.parse(stored);if(!session.refresh_token)throw new Error("Saved session is incomplete.");if(!session.expires_at||session.expires_at*1000<=Date.now()+60000){const response=await fetch(`${config.supabaseUrl}/auth/v1/token?grant_type=refresh_token`,{method:"POST",headers:{apikey:config.anonKey,"Content-Type":"application/json"},body:JSON.stringify({refresh_token:session.refresh_token})});const refreshed=await response.json();if(!response.ok)throw new Error(refreshed.error_description||refreshed.message||"Session expired.");session=refreshed;localStorage.setItem(RSVP_SESSION_KEY,JSON.stringify(session))}window.location.replace("rsvp.html")}catch(error){localStorage.removeItem(RSVP_SESSION_KEY);loginStatus.textContent="Your session expired. Please log in again."}}

async function getConfig(){if(window.WEDDING_CONFIG?.supabaseUrl&&window.WEDDING_CONFIG?.anonKey)return window.WEDDING_CONFIG;const response=await fetch("/api/upload-config",{cache:"no-store"});const value=await response.json();if(!response.ok)throw new Error(value.error||"Login is not configured.");return value}
