const authSection=document.querySelector("#authSection"),rsvpSection=document.querySelector("#rsvpSection"),authForm=document.querySelector("#authForm"),rsvpForm=document.querySelector("#rsvpForm"),authStatus=document.querySelector("#authStatus"),rsvpStatus=document.querySelector("#rsvpStatus"),logoutButton=document.querySelector("#logoutButton");
const RSVP_SESSION_KEY="weddingRsvpSession";
let session=null,config=null;
authForm.onsubmit=authenticate;rsvpForm.onsubmit=saveRsvp;logoutButton.onclick=logout;
restoreSession();
async function authenticate(event){event.preventDefault();const button=document.querySelector("#authSubmit");button.disabled=true;authStatus.textContent="Creating account…";try{config=await getConfig();const response=await fetch(`${config.supabaseUrl}/auth/v1/signup`,{method:"POST",headers:{apikey:config.anonKey,"Content-Type":"application/json"},body:JSON.stringify({email:document.querySelector("#email").value.trim(),password:document.querySelector("#password").value})});const result=await response.json();if(!response.ok)throw new Error(result.error_description||result.msg||result.message||"Unable to create account.");if(!result.access_token){authStatus.textContent="Account created. Check your email to confirm it, then use the Login page.";return}saveSession(result);await openRsvp()}catch(error){authStatus.textContent=error.message}finally{button.disabled=false}}
function saveSession(value){session=value;localStorage.setItem(RSVP_SESSION_KEY,JSON.stringify(value))}
async function restoreSession(){const stored=localStorage.getItem(RSVP_SESSION_KEY);if(!stored)return;try{config=await getConfig();session=JSON.parse(stored);if(!session.refresh_token)throw new Error("Saved session is incomplete.");if(!session.expires_at||session.expires_at*1000<=Date.now()+60000){const response=await api("/auth/v1/token?grant_type=refresh_token",{method:"POST",headers:{apikey:config.anonKey,"Content-Type":"application/json"},body:JSON.stringify({refresh_token:session.refresh_token})});const refreshed=await response.json();if(!response.ok)throw new Error(refreshed.error_description||refreshed.message||"Session expired.");saveSession(refreshed)}await openRsvp()}catch(error){localStorage.removeItem(RSVP_SESSION_KEY);session=null;window.location.replace("login.html?expired=1")}}
async function openRsvp(){authSection.hidden=true;rsvpSection.hidden=false;logoutButton.hidden=false;const userResponse=await api("/auth/v1/user",{headers:authHeaders()});if(!userResponse.ok)throw new Error("Unable to restore your account session.");session.user=await userResponse.json();localStorage.setItem(RSVP_SESSION_KEY,JSON.stringify(session));const response=await api(`/rest/v1/rsvps?select=*&user_id=eq.${encodeURIComponent(session.user.id)}`,{headers:authHeaders()});if(!response.ok)return;const rows=await response.json();if(rows[0]){const row=rows[0];document.querySelector("#familyName").value=row.family_name;document.querySelector(`input[name=attending][value="${row.attending}"]`).checked=true;document.querySelector("#adultCount").value=row.adult_count;document.querySelector("#childCount").value=row.child_count;document.querySelector("#notes").value=row.notes||""}}
async function saveRsvp(event){event.preventDefault();const button=rsvpForm.querySelector("button[type=submit]"),attending=document.querySelector("input[name=attending]:checked").value==="true",adults=Number(document.querySelector("#adultCount").value),children=Number(document.querySelector("#childCount").value);if(attending&&adults+children<1){rsvpStatus.textContent="Enter at least one guest.";return}button.disabled=true;rsvpStatus.className="status";rsvpStatus.textContent="Saving…";const response=await api("/rest/v1/rsvps?on_conflict=user_id",{method:"POST",headers:{...authHeaders(),"Content-Type":"application/json",Prefer:"resolution=merge-duplicates,return=representation"},body:JSON.stringify({user_id:session.user.id,family_name:document.querySelector("#familyName").value.trim(),attending,adult_count:attending?adults:0,child_count:attending?children:0,notes:document.querySelector("#notes").value.trim()||null})});button.disabled=false;if(!response.ok){const error=await response.json();rsvpStatus.textContent=error.message||"Unable to save reservation.";return}rsvpStatus.className="status success";rsvpStatus.textContent="Your reservation has been saved. Thank you!"}
function authHeaders(){return{apikey:config.anonKey,Authorization:`Bearer ${session.access_token}`}}
function api(path,options={}){return fetch(`${config.supabaseUrl}${path}`,options)}
function logout(){localStorage.removeItem(RSVP_SESSION_KEY);session=null;window.location.replace("login.html")}
async function getConfig(){if(window.WEDDING_CONFIG?.supabaseUrl&&window.WEDDING_CONFIG?.anonKey)return window.WEDDING_CONFIG;const response=await fetch("/api/upload-config",{cache:"no-store"});const value=await response.json();if(!response.ok)throw new Error(value.error||"RSVP is not configured.");return value}
